/**
 * @file vite-env.d.ts
 * Type declarations for Vite-specific module imports:
 * - CSS Modules (*.module.css)
 * - Static image assets (*.png, *.svg, *.jpg, *.jpeg, *.gif, *.webp)
 * - Web Audio API extensions for the ambient sound mixer.
 */

// ============================================================================
// CSS Declarations
// ============================================================================

/** Allows importing plain CSS files as side-effects (e.g. global styles). */
declare module "*.css" {
    const content: Record<string, string>;
    export default content;
}

// ============================================================================
// CSS Module Declarations
// ============================================================================

/** Allows importing CSS Modules and accessing scoped class names. */
declare module "*.module.css" {
    /** Scoped CSS class name map generated by Vite's CSS Modules pipeline. */
    const classes: { readonly [key: string]: string };
    export default classes;
}

// ============================================================================
// Static Asset Declarations
// ============================================================================

declare module "*.png" {
    const src: string;
    export default src;
}

declare module "*.svg" {
    const src: string;
    export default src;
}

declare module "*.jpg" {
    const src: string;
    export default src;
}

declare module "*.jpeg" {
    const src: string;
    export default src;
}

declare module "*.gif" {
    const src: string;
    export default src;
}

declare module "*.webp" {
    const src: string;
    export default src;
}

declare module "*.ico" {
    const src: string;
    export default src;
}

// ============================================================================
// Web Audio API Interfaces (Ambient Sound Mixer)
// ============================================================================

/** Extended AudioBufferSourceNode for the ambient sound mixer. */
interface AmbientAudioSource extends AudioBufferSourceNode {
    /** The gain node controlling this source's volume. */
    gainNode: GainNode;
    /** Reference to the audio buffer loaded for this source. */
    buffer: AudioBuffer;
}

/** Options for creating an ambient audio source. */
interface AmbientAudioOptions {
    /** Unique identifier for the audio source. */
    id: string;
    /** URL of the audio resource. */
    url: string;
    /** Initial volume (0.0 to 1.0). Default: 1.0 */
    volume?: number;
    /** Whether to loop the audio. Default: true */
    loop?: boolean;
}

/** Configuration for the ambient sound mixer. */
interface AmbientMixerConfig {
    /** Master volume (0.0 to 1.0). */
    masterVolume: number;
    /** Per-channel volumes keyed by channel ID. */
    channelVolumes: Record<string, number>;
    /** Whether the mixer is currently muted. */
    muted: boolean;
}

// ============================================================================
// Error Status Extension (for API errors with HTTP status codes)
// ============================================================================

interface Error {
    /** HTTP status code from the failed API request. */
    status?: number;
    /** Retry-After header value from 429/503 responses. */
    retryAfter?: string | null;
    /** Exact server-specified rate-limit reset delay in ms (x-ratelimit-reset-*). */
    rateLimitResetMs?: number | null;
    /** Circuit breaker error code (e.g., "CIRCUIT_OPEN"). */
    code?: string;
    /** The last error message from the circuit breaker. */
    lastError?: string | null;
}
